name: My Service Build and Deploy
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "URL to run tests against"
        required: true
        default: https://my-site.com
jobs:
  deploy_staging:
    name: Staging Deploy
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Logging the Staging release
        run: echo "This run is the staging deployment"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set URL to pass to Tests
        run: |
          echo "ENVIRONMENT=http://my-site.com" >> $GITHUB_ENV
      - name: Build and Deploy
        run: |
          echo "Build and Deploy"
      - name: Kick Off Playwright Test Job
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: djewsanchez/pw-bp
          event-type: run-my-tests
          client-payload: '{"github": ${{ toJson(github) }}}'
      - name: Wait for Automation Repo Workflow
        uses: peter-evans/wait-for-workflow@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          owner: djewsanchez
          repo: pw-bp
          workflow: playwright.yml # workflow file in automation repo
          ref: main # branch to wait on
          check-run-name: Playwright Tests
          wait-for-completion: true
          conclusion: success # fail if the workflow conclusion is not success
          poll-interval-seconds: 15
